name: Build R-Type

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    build_on_linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/Checkout@v4
              with:
                submodules: true
            - name: Install dependencies
              run: |
                sudo apt update
                apt install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev -y

            
            - name: run cmake
              run: cmake -B build .

            - name: run make
              run: |
                cd build/
                make
