name: Check clang-format

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-clang-format:
    name: verify clang-format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Clang-Format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Vérifier clang-format
      run: |
        files=$(find . -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.hpp')
        if [ -n "$files" ]; then
          clang-format --dry-run --Werror $files | while read -r line; do
            if [[ "$line" == *"error"* ]]; then
              file=$(echo "$line" | cut -d ':' -f 1)
              line_num=$(echo "$line" | cut -d ':' -f 2)
              echo "::error file=$files,line=$line_num"
            fi
          done
        else
          echo "::notice ::No files to check."
        fi
