name: Epitech - Upload to main

on:
    push:
        branches:
            - main

jobs:
    push_to_mirror:
        name: Push to mirror
        runs-on: ubuntu-latest
        steps:
            - name: git-sync
              uses: wei/git-sync@v3
              with:
                  source_repo: ${{ secrets.SOURCE_REPO }}
                  source_branch: "main"
                  destination_repo: ${{ secrets.DEST_REPO }}
                  destination_branch: "main"
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
